### ISSUE TITLE
Did you test your DKM in the Aachen Benchmark ?

### ISSUE THREAD

**Issue by noone-code** [Parskatt/DKM#14]
Like SuperGlue and LoFTR did

**Comment by Parskatt** [comment]
Some additional context for localization/ vs matching:

![image](https://user-images.githubusercontent.com/22053118/205926082-4b211e2b-6501-4c28-a595-e8f35003a728.png)

Basically matching methods do not really improve results on Aachen in general, however I don't think this is due to lack of improvement in the matching methods themselves but rather on how they are evaluated (judging from the results of recent IMC challenges it is clear that LoFTR and follow-ups perform superior to SuperGlue). I therefore don't find it a relevant benchmark.

**Comment by noone-code** [comment]
Yep, I agree with you for this point.
> Basically matching methods do not really improve results on Aachen in general
